language: ruby
rvm:
- 2.3.6

env:
  global:
    secure: erCrzjQaYr1nm1EPhPy23uDWI/VYIkp3BBZGAtEe80gLJGx8NW174LuC8rgLztfCOQ2Vdc9jNIWRufhqbmF2Bw4pMcuDlSrmuIuhj+IxCq0IZsZdeYBMUZXqp6Lr1g4RlJkmR+mjvoTr7nFCh4HDhunifAipKsnMzQUx15MK0DQ=

before_script:
- psql -c 'create role sample_app_3_1 SUPERUSER LOGIN;' postgres
- psql -c 'create role whitemac       SUPERUSER LOGIN;' postgres
- psql -c 'create database sample_app_3_1_test;' -U postgres postgres
- bundle exec rake db:migrate

cache: bundler

sudo: false
